使用了docker task，但是一直失败，镜像起不来，怀疑是提供的task的问题

ts=2024-08-31T06:06:28.158Z caller=exporter.go:152 level=error msg="Error pinging mysqld" err="dial tcp 172.18.0.4:3306: connect: connection refused"

为什么通过我们的流程数据库乱码，他不用我们的流程就没有问题，怀疑是我们这边什么配置要加或者是task有问题
经过日志分析和调查，我们这边也经过分析之后尝试同样的步骤可以重现问题，发现问题是它的dockerfile写的有问题



